services:
  # --- GATEWAY ---
  nginx:
    image: nginx:alpine
    profiles: ["dev-full", "prod"]
    container_name: gateway_nginx
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./gateway/.htpasswd:/etc/nginx/.htpasswd:ro
    networks:
      - public_net
      - private_net
    depends_on:
      - backend-app
      - grafana

  # --- INFRAESTRUTURA ---
  redis:
    image: redis:7-alpine
    profiles: ["dev", "dev-full", "prod"]
    container_name: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - private_net

  postgres:
    image: postgres:16-alpine
    profiles: ["dev-full", "prod"]
    container_name: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - private_net

  backend-app:
    profiles: ["dev-full", "prod"]
    build: .
    image: backend-arena-mafia
    environment:
      # Database Configuration
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

      # JWT Configuration
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}

      # Spring Configuration
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME}

      # Redis Configuration
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

      # AWS Configuration (SQS)
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}

      # SMS Configuration
      - COMTELE_API_URL=${COMTELE_API_URL}
      - COMTELE_API_KEY=${COMTELE_API_KEY}

      # OpenTelemetry Configuration
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_PROTOCOL=${OTEL_EXPORTER_OTLP_PROTOCOL}
      - OTEL_LOGS_EXPORTER=${OTEL_LOGS_EXPORTER}
      - OTEL_METRICS_EXPORTER=${OTEL_METRICS_EXPORTER}
      - OTEL_TRACES_EXPORTER=${OTEL_TRACES_EXPORTER}
      - OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME}
      - OTEL_RESOURCE_ATTRIBUTES=${OTEL_RESOURCE_ATTRIBUTES}
    depends_on:
      otel-collector:
        condition: service_started
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
        required: false
    networks:
      - private_net
    labels:
      service: "backend-api"
      container_name: "spring-app"

  # --- OBSERVABILIDADE ---
  prometheus:
    profiles: ["dev", "dev-full", "prod"]
    image: prom/prometheus:v3.9.0
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - private_net

  loki:
    profiles: ["dev", "dev-full", "prod"]
    image: grafana/loki:3.0.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki.yml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki
    networks:
      - private_net

  tempo:
    profiles: ["dev", "dev-full", "prod"]
    image: grafana/tempo:2.4.1
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yml:/etc/tempo.yaml:ro
      - tempo-data:/var/tempo
    networks:
      - private_net

  grafana:
    profiles: ["dev", "dev-full", "prod"]
    image: grafana/grafana:10.3.0
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_CSRF_ALWAYS_CHECK=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_DISABLE_LOGIN_FORM=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./config/grafana/dashboards:/etc/grafana/dashboards:ro
    networks:
      - private_net
    depends_on:
      - loki
      - tempo
      - prometheus

  otel-collector:
    profiles: ["dev", "dev-full", "prod"]
    image: otel/opentelemetry-collector-contrib:0.96.0
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./config/otel-collector-config.yml:/etc/otel-collector-config.yml
    networks:
      - private_net
    depends_on:
      - loki
      - tempo

# --- REDES ---
networks:
  public_net:
    driver: bridge
  private_net:
    driver: bridge
    internal: true

# --- VOLUMES ---
volumes:
  postgres-data:
  prometheus-data:
  loki-data:
  tempo-data:
  grafana-data: